# Generated by Django 4.2.7 on 2025-08-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('stationery', 'Stationery'), ('electronics', 'Electronics'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
