# Generated by Django 4.2.7 on 2025-08-09 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='qr_validity_minutes',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
