# Generated by Django 4.2.7 on 2025-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_shop_qr_validity_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('food', 'Food'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('stationery', 'Stationery'), ('electronics', 'Electronics'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
