# Generated by Django 4.2.7 on 2025-08-11 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sub_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
