# Generated by Django 4.2.23 on 2025-08-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_shop_disabled_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_mode',
            field=models.CharField(choices=[('stock', 'Stock'), ('live_stock', 'Live Stock')], default='stock', max_length=20),
        ),
    ]
