# Generated by Django 5.2 on 2025-11-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_stock_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
