# Generated by Django 5.2 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_otp_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('IT', 'Information Technology'), ('AIDS', 'Artificial Intelligence and Data Science'), ('CSBS', 'Computer Science and Business Systems')], help_text='Department (for students)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], help_text='Academic year (for students)', max_length=20, null=True),
        ),
    ]
