# Generated by Django 5.2 on 2025-11-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_department_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department code (for students)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, help_text='Academic year code (for students)', max_length=20, null=True),
        ),
    ]
