# Generated by Django 5.2 on 2025-11-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_department_alter_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shopAdmin', 'Shop Admin'), ('student', 'Student'), ('staff', 'Staff')], default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
