# Generated by Django 5.2 on 2025-11-29 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_staff_code_alter_user_role_alter_user_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_shops', 'View Shops'), ('view_products', 'View Products'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('place_order', 'Place Order'), ('view_order', 'View Order'), ('cancel_order', 'Cancel Order'), ('add_balance', 'Add Balance'), ('view_profile', 'View Profile'), ('update_profile', 'Update Profile'), ('view_transactions', 'View Transactions'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_logs', to='api.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_logs', to='api.product')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_logs', to='api.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='student_log_created_a9e3b6_idx'), models.Index(fields=['user', '-created_at'], name='student_log_user_id_ba2d4f_idx'), models.Index(fields=['action', '-created_at'], name='student_log_action_2d1692_idx')],
            },
        ),
    ]
