# Generated by Django 5.2 on 2025-11-27 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_enabled', models.BooleanField(default=True, help_text='Allow users to login')),
                ('registration_enabled', models.BooleanField(default=True, help_text='Allow new user registration')),
                ('ordering_enabled', models.BooleanField(default=True, help_text='Allow users to place orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
                'db_table': 'site_configuration',
            },
        ),
    ]
