# Generated by Django 5.2 on 2025-11-27 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Year code (e.g., '1', '2', '3', '4')", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'First Year', 'Second Year')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show this year in registration')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_years',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Department code (e.g., 'CSE', 'ECE')", max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full department name', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show this department in registration')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['order', 'code'],
            },
        ),
    ]
