# Generated by Django 5.2 on 2025-11-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_academicyear_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='restricted_departments_login',
            field=models.JSONField(blank=True, default=list, help_text="List of department codes that are restricted from login (e.g., ['CSE', 'ECE'])"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='restricted_departments_ordering',
            field=models.JSONField(blank=True, default=list, help_text="List of department codes that are restricted from ordering (e.g., ['CSE', 'ECE'])"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='restricted_departments_registration',
            field=models.JSONField(blank=True, default=list, help_text="List of department codes that are restricted from registration (e.g., ['CSE', 'ECE'])"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='restricted_years_login',
            field=models.JSONField(blank=True, default=list, help_text="List of year codes that are restricted from login (e.g., ['1', '2'])"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='restricted_years_ordering',
            field=models.JSONField(blank=True, default=list, help_text="List of year codes that are restricted from ordering (e.g., ['1', '2'])"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='restricted_years_registration',
            field=models.JSONField(blank=True, default=list, help_text="List of year codes that are restricted from registration (e.g., ['1', '2'])"),
        ),
    ]
