# Generated by Django 5.2 on 2025-11-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_siteconfiguration_restricted_departments_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_expiration_hours',
            field=models.IntegerField(default=24, help_text='Number of hours after which unpaid/unverified orders expire (default: 24 hours)'),
        ),
    ]
