# Generated by Django 5.2 on 2025-11-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_siteconfiguration_order_expiration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='order_expiration_hours',
        ),
    ]
